#include "ContadorDescendente.h" //BIEN
#include "oled96.h" //BIEN
#include "MYIPFILTRO2324.h" //BIEN
#include "IPMotorDC.h" //BIEN
#include "xil_io.h" //BIEN
#include "myipPasoAPaso.h" //BIEN
#include "myipRGB3Pines.h"//BIEN
#include "myipSensorUltraSound.h" //BIEN
#include "MY_IP_DS18B20_AZM.h"//BIEN
#include "SensorHall.h"//BIEN
#include "xuartlite.h"
#include "xiic.h"
#include "xgpio.h"
#include "xparameters.h"
#include "xspi.h"
#include "xbram.h"
#include "MY_IP_TEMP_Y_UMEDAD.h"
#include "IPservoMotor.h"
#include "xil_printf.h"
#include "xuartlite.h"
#include "xtmrctr.h"
#include "time.h"


#define LEDMask 			0xF
#define buttonMask			0x0
#define DIR_CONTADOR 		XPAR_CONTADORDESCENDENTE_0_S00_AXI_BASEADDR //BIEN
#define DIR_IPMOTORDC		XPAR_IPMOTORDC_0_S00_AXI_BASEADDR //BIEN
#define DIR_ENTRADAPIN		XPAR_MYIPFILTRO2324_0_S00_AXI_BASEADDR  //BIEN
#define DIR_PID 			XPAR_HDL_DUT_F_IP_0_BASEADDR
#define DIR_SENSORHALL		XPAR_SENSORHALL_0_S00_AXI_BASEADDR //BIEN
#define DIR_BRAM			XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR //BIEN
#define DIR_FC				XPAR_AXI_GPIO_FC_DEVICE_ID  //FC //BIEN
#define DIR_BOTONESLED		XPAR_AXI_GPIO_BTNLEDS_DEVICE_ID //Botones y led //BIEN
#define DIR_CS				XPAR_AXI_GPIO_CS_DEVICE_ID //CS y CAL //BIEN
#define DIR_CAL				XPAR_AXI_GPIO_CAL_DEVICE_ID
#define DIR_SWICH			XPAR_AXI_GPIO_SW_DEVICE_ID //Swich //BIEN
#define DIR_PASOAPASO 		XPAR_MYIPPASOAPASO_0_S00_AXI_BASEADDR  //BIEN
#define DIR_RGB1			XPAR_MYIPRGB3PINES_0_S00_AXI_BASEADDR  //BIEN
#define DIR_RGB2			XPAR_MYIPRGB3PINES_1_S00_AXI_BASEADDR //BIEN
#define DIR_DISTANCIA		XPAR_MYIPSENSORULTRASOUND_0_S00_AXI_BASEADDR  //BIEN
#define DIR_TERMOMETRO		XPAR_MY_IP_DS18B20_AZM_0_S00_AXI_BASEADDR //BIEN
#define DIR_UART			XPAR_AXI_UARTLITE_0_BASEADDR //BIEN
#define DIR_SPI 			XPAR_AXI_QUAD_SPI_0_BASEADDR
#define DIR_SERVO 			XPAR_IPSERVOMOTOR_0_S00_AXI_BASEADDR
#define DIR_TEMPERATURA		XPAR_MY_IP_TEMP_Y_UMEDAD_0_S00_AXI_BASEADDR
#define DIR_TIMER			XPAR_AXI_TIMER_0_BASEADDR


#define CONTADOR_RESET 		CONTADORDESCENDENTE_S00_AXI_SLV_REG0_OFFSET
#define CUENTA 				CONTADORDESCENDENTE_S00_AXI_SLV_REG1_OFFSET
#define FILTROAV_RESET		MYIPFILTRO2324_S00_AXI_SLV_REG0_OFFSET
#define SALIDA_FILTROAV		MYIPFILTRO2324_S00_AXI_SLV_REG1_OFFSET
#define MOTORDC_RESET		IPMOTORDC_S00_AXI_SLV_REG0_OFFSET
#define MOTORDC_SENTIDO		IPMOTORDC_S00_AXI_SLV_REG1_OFFSET
#define MOTORDC_DUTY		IPMOTORDC_S00_AXI_SLV_REG2_OFFSET
#define MOTORDC_FREQCLK		IPMOTORDC_S00_AXI_SLV_REG3_OFFSET
#define MOTORDC_FREQPWM		IPMOTORDC_S00_AXI_SLV_REG4_OFFSET
#define MOTORDC_ERROR		IPMOTORDC_S00_AXI_SLV_REG5_OFFSET
#define RESET_TEMPERATURA 	MY_IP_TEMP_Y_UMEDAD_S00_AXI_SLV_REG0_OFFSET
#define LED_TEMPERATURA 	MY_IP_TEMP_Y_UMEDAD_S00_AXI_SLV_REG1_OFFSET
#define ERROR_CHECKSUM_TEMPERATURA MY_IP_TEMP_Y_UMEDAD_S00_AXI_SLV_REG2_OFFSET
#define ERROR_TIMMING_TEMPERATURA 	MY_IP_TEMP_Y_UMEDAD_S00_AXI_SLV_REG3_OFFSET
#define CODE_ERROR_TEMPERATURA	 MY_IP_TEMP_Y_UMEDAD_S00_AXI_SLV_REG4_OFFSET
#define QUE_VER_TEMPERATURA 	MY_IP_TEMP_Y_UMEDAD_S00_AXI_SLV_REG5_OFFSET
#define RESET_STEPPER 	 	MYIPPASOAPASO_S00_AXI_SLV_REG0_OFFSET
#define FREC_RELOJ_STEPPER 	MYIPPASOAPASO_S00_AXI_SLV_REG1_OFFSET
#define ENABLE_STEPPER 		MYIPPASOAPASO_S00_AXI_SLV_REG2_OFFSET
#define DIR_STEPPER 		MYIPPASOAPASO_S00_AXI_SLV_REG3_OFFSET
#define FREC_PASO_STEPPER 	MYIPPASOAPASO_S00_AXI_SLV_REG4_OFFSET
#define RGB_RESET			MYIPRGB3PINES_S00_AXI_SLV_REG0_OFFSET
#define RGB_FRECCLK			MYIPRGB3PINES_S00_AXI_SLV_REG1_OFFSET
#define RGB_FRECPWM			MYIPRGB3PINES_S00_AXI_SLV_REG2_OFFSET
#define RGB_R				MYIPRGB3PINES_S00_AXI_SLV_REG3_OFFSET
#define RGB_G				MYIPRGB3PINES_S00_AXI_SLV_REG4_OFFSET
#define RGB_B				MYIPRGB3PINES_S00_AXI_SLV_REG5_OFFSET
#define RGB_ERROR			MYIPRGB3PINES_S00_AXI_SLV_REG6_OFFSET
#define RESET_HCS 			MYIPSENSORULTRASOUND_S00_AXI_SLV_REG0_OFFSET
#define FREC_RELOJ_HCS 		MYIPSENSORULTRASOUND_S00_AXI_SLV_REG1_OFFSET
#define DIST_HCS 			MYIPSENSORULTRASOUND_S00_AXI_SLV_REG2_OFFSET
#define TEMP_INT 			MY_IP_DS18B20_AZM_S00_AXI_SLV_REG0_OFFSET
#define TEMP_DEC 			MY_IP_DS18B20_AZM_S00_AXI_SLV_REG1_OFFSET
#define RESET_HALL 			SENSORHALL_S00_AXI_SLV_REG0_OFFSET
#define SALIDA_HALL 		SENSORHALL_S00_AXI_SLV_REG2_OFFSET
#define SENTIDO_HALL 		SENSORHALL_S00_AXI_SLV_REG1_OFFSET
#define SERVORESET 			IPSERVOMOTOR_S00_AXI_SLV_REG0_OFFSET
#define ServoPWM  			IPSERVOMOTOR_S00_AXI_SLV_REG1_OFFSET

#define PID_RESET      	 	0x0  //write 0x1 to bit 0 to reset IP core
#define PID_ENABLE      	0x4  //enabled (by default) when bit 0 is 0x1
#define PID_STROBE     		0x8  //write 1 to bit 0 after write all input data
#define PID_READY       	0xC  //wait until bit 0 is 1 before read output data
#define PID_TIMESPAN   		0x10  //contains unique IP timestamp (yymmddHHMM): 2311201810
#define PID_Consigna      	0x100  //data register for Inport Consigna
#define PID_KP             	0x104  //data register for Inport P
#define PID_KI             	0x108  //data register for Inport I
#define PID_SENSOR        	0x10C  //data register for Inport Sensor
#define PID_OUTPUT        	0x110  //data register for Outport Salida

float velocidad();
int iniciamemorias();
int RGB1(int R, int G, int B);
int RGB2(int R, int G, int B);
float temperaturaNTC();
int distancia();
int motorDCfun(int Sentido, int Duty);
void motorPasoAPaso(int Direccion, int paso);
float temperaturaDHT11();
float humedadDHT11();
void servogrados(float grados);
long escribeBRAM(int i, int ESTADO, float valor, u64 cuenta);
int leeBRAM(int i);
int uartbotones(u32 DatosRecividos);
int contador();
